### PR TITLE
Setup controller

### PR DESCRIPTION
**Pull request by hellais**
This contains the local playbook to be executed on the controller host to setup all the user accounts and install all the required packages.

The ssh_users role we should then declare it in the meta as a dep for any other playbook we run on remote hosts so we can always ensure everyone has access to hosts they should have access to.

This is the last piece needed to close: https://github.com/ooni/devops/issues/67

### CODE REVIEW

**Comment by hellais** [comment]
I realized now that I am missing 2 critical pieces:
* [ ] Add support for passwordless sudo for all admin users
* [ ] Clone the devops repo in a directory that is readable by all admin users instead of the ubuntu home

**Comment by hellais** [comment]
Ok it's now done.

**Review by DecFox — APPROVED** [review]
LGTM!

**Comment by hellais** [comment]
This is deployed, so I am merging.

**Pull request merged**
